// chapter_5.typ

#import "./../../template_notes.typ": *
#show: template

// set up heading numbering
#set heading(numbering: "1.")
#counter(heading).update(6)
#context {
  if target() == "paged" and sys.inputs.at("individualchs", default: "false") == "true" {
    [#counter(heading).update(5)
      = Applications of Integrals
      #context counter(heading).step(level: 2)
      == Volumes by Cross-Sections, Disks, and Washers
      #set document(title: "Section 6.2 Day 2")]
  } else {
    [#context counter(heading).step(level: 2)
      #context counter(heading).step(level: 2)]
  }
}
#context counter(heading).step(level: 3)

// any functions and templating you want for just this chapter can go here




=== Solids of Revolution: The Disk method
#emph-block[
  6.2b Learning Objectives:
  - I can use disk or washer method to find the volume of a _solid of revolution_. I can recognize that these methods are related to finding the area between curves.
]

#definition[
  A _solid of revolution_ is the solid generated by rotating (or revolving) a plane region about an axis in its plane.
]

Consider the function #math.equation($y=sqrt(x)$, alt: "y equals square root of x") on #math.equation($[0,4]$, alt: "the closed interval from 0 to 4"). Imagine rotating it all the way around the #acc("x")-axis to form a solid:
#figure()[
  #box(
    image(
      "figures/introtorevs.svg",
      alt: "graph of y equals square root of x from 0 to 4, the region between the function and the x-axis is shaded",
      width: 40%,
    ),
  )#h_html(3mm)
  #box(
    image(
      "figures/introtorevs2.svg",
      alt: "graph of y equals square root of x from 0 to 4, the region between the function and the x-axis is shaded",
      width: 50%,
    ),
  )
]

#note-block[If we wish to find the volume of this solid, we have only added one step to our process from before. After that we have the same type of problem as the ones with the cross-sections. We have to build the 2-D region we want to form the solid from.
  1. Sketch the function and its reflection about the axis you are told to revolve around. This with the domain give you the 2-D region we go from.
  2. Imagine circular cross-sections that are perpendicular to the same axis you just used.
  3. Continuing as before the cross-sections will _always_ be circular and have radius equal to the function value.
]

We can make this more specific below.
#theorem[Volume by Disks for Rotation about the #acc("x")-axis][
  To find the volume of a solid formed by rotating a function #math.equation($y=f(x)$, alt: "y equals f of x") on #math.equation($[a,b]$, alt: "the closed interval from a to b") about the #acc("x")-axis first note that the area of each cross-section is #math.equation($A(x) = pi (f(x))^2$, alt: "capital a of x is pi times f of x squared"), then the volume is
  #math.equation(
    $V=integral_a^b A(x) dif x = integral_a^b pi (f(x))^2 dif x.$,
    alt: "v equals the integral from a to b of capital a of x, d x which is just the integral from a to b of pi times the square of f of x, d x.",
    block: true,
  )
]

#exercise[
  Write a similar statement to the one above for rotating a function #math.equation($y=f(x)$, alt: "y equals f of x") for #acc("y") values in #math.equation($[a,b]$, alt: "the closed interval from a to b") about the #acc("y")-axis. _Hint: careful with the variables you use in the expression. The variable of integration should be the variable used in the integrand._
]

#example[
  Set up an integral to find the volume of the solid generated by revolving the region in the first quadrant bounded above by #math.equation($y=-2x^2+2$, alt: "y equals negative 2 x squared plus 2") around the #acc("x")-axis.

  Set up an integral to find the volume when revolving this same region around the #acc("y")-axis.
]

#my-solution-block[
  The solid looks like
  #figure(image(
    "figures/firstdiskex.svg",
    alt: "view of y equals negative 2 x squared plus 2 and its reflection across the x axis from the side. At this angle we can see disks perpendicular to the x axis with radius lining up with the curves from x equals 0 to x equals 1.",
    width: 50%,
  ))

  However, this might be difficult to draw by hand. An alternative is to just draw the curve in 2-D, its reflection, and a single cross-section to help visualize the radius of the disks. This looks like
  // TODO: adjust ellipses to be dashed in the back in this figure
  #figure(image(
    "figures/firstdiskexsketch.svg",
    alt: "view of y equals negative 2 x squared plus 2 and its reflection across the x axis. there is a single disk sketched around x equals 0 point 2 5 that has radius lining up with the curves.",
    width: 50%,
  ))

  Then, we need to find where the curve hits the #acc("x")-axis. Sometimes we can tell from the graph we draw, sometimes we have to solve for it
  #math.equation(
    $
           -2x^2+2 & = 0 \
         -2(x^2-1) & = 0 \
      -2(x+1)(x-1) & = 0 \
                 x & = 1,-1
    $,
    alt: "solving negative 2 x squared plus 2 equals 0 by factoring to negative 2 times x plus 1 times x minus 1 equals 0. so x is 1 or negative 1.",
    block: true,
  )
  Since we are looking in the first quadrant, #math.equation($x=1$, alt: "x equals 1") is where this intersection happens (This is one of the bounds for the integral later). The area of the circular cross-section is #math.equation($pi r^2 = pi (-2x^2+2)^2$, alt: "pi r squared or rather, pi times negative 2 x squared plus 2 squared"). Thus, the integral we need is
  #math.equation(
    $V = integral_0^1 pi (-2x^2+2)^2 dif x.$,
    alt: "v equals the integral from 0 to 1 of pi times negative 2 x squared plus 2 squared.",
  )
]

#exercise[Evaluate the integral above to find the volume of the solid.]
#exercise[Set up and solve an integral to find the volume when revolving this same region around the #acc("y")-axis.]

#theorem[Volume by Disks for Rotation about the #acc("y")-axis][
  To find the volume of a solid formed by rotating a function #math.equation($y=f(x)$, alt: "y equals f of x") (and solving for #math.equation($x=f^(-1)(y)$, alt: "x equals f inverse of y")) for #acc("x") in #math.equation($[a,b]$, alt: "the closed interval from a to b") and #acc("y") between #math.equation($f(a)$, alt: "f of a") and #math.equation($f(b)$, alt: "f of b") about the #acc("y")-axis first note that the area of each cross-section is #math.equation($A(y) = pi (f^(-1)(y))^2$, alt: "capital a of x is pi times f inverse of x squared"), then the volume is
  #math.equation(
    $V=integral_(f(a))^(f(b)) A(y) dif y = integral_(f(a))^(f(b)) pi (f^(-1)(y))^2 dif y.$,
    alt: "v equals the integral from a to b of capital a of x, d x which is just the integral from a to b of pi times the square of f of x, d x.",
    block: true,
  )
]
In other words,
#note-block[
  *Finding the Volume of a Solid of Revolution: Disk Method*
  1. Sketch both the region that is being rotated and the axis of revolution.
  2. Determine the variable of integration. Integration is performed with respect to the axis that is perpendicular to the slices.
  3. Determine the limits of integration. They must match the variable of integration!
  4. Derive a formula for the radius of the disk.
  5. Integrate. Remember units in your final answer when applicable.
]

=== Solids of Revolution: The Washer Method
Note that we can only use the disk method if the cross-sections of the solid of revolution are circles. This means that there is no space gap between the region and the axis of revolution. What if there is a gap between the region and the axis of revolution?

#example[
  Set up an integral to find the volume of the solid generated by revolving the region in the first quadrant bounded by #math.equation($y = x^2$, alt: "y equals x squared") and #math.equation($y = sqrt(x)$, alt: "y equals square root x") around the #acc("x")-axis.
]
#my-solution-block[
  // TODO: adjust ellipses to be dashed in the back in this figure

  #figure()[
    #box(baseline: (at: horizon, shift: 0% + 0pt), image(
      "figures/firstwasherexsketch.svg",
      alt: "a sketch of the curves y equals x squared and y equals square root x from x equals 0 to 1. The reflections across the vertical axis are also shown, and a single cross-section around x equals one half is drawn. The cross-section is 2 concentric rings with radii little r and big R lining up with y equals x squared and y equals square root x respectively.",
      width: 45%,
    ))#h_html(2mm)
    #box(baseline: (at: horizon, shift: 0% + 13pt), image(
      "figures/washercrosssection.svg",
      alt: "a sketch of 2 concentric circles. The smaller circle has radius little r and the larger circle has radius big R. The space between them is shaded blue, making a washer or flat donut shape.",
      width: 30%,
    ))
  ]


  We note the curves intersect at #coord("1", "1"). There are a few ways to think about this problem, but for now let's go back to thinking about the area of the cross-section and integrating that from 0 to 1 in #acc("x"). For the cross-sections, the area is a circle with radius #math.equation($R=sqrt(x)$, alt: "big r equals square root of x") minus the area of a smaller circle with area #math.equation($r=x^2$, alt: "little r equals x squared"). This region is sketched above in blue, and is known as a washer (as in the metal bit used with a nut and bolt that has the same shape). The area of the full region is the difference in areas between the 2 circles. That is, #math.equation($A(x)=pi R(x)^2 - pi r(x)^2$, alt: "a of x is pi times big R of x squared minus pi times little r of x squared.").
  Then, integrating along the axis perpendicular to the cross-sectional area, we see the volume is
  #math.equation(
    $
      V & = integral_0^1 A(x) dif x \
        & = integral_0^1 pi R(x)^2 - pi r(x)^2 dif x \
        & = pi integral_0^1 [(sqrt(x))^2-(x^2)^2] dif x \
        & = pi integral_0^1 x - x^4 dif x
    $,
    alt: "the volume is the integral from 0 to 1 of a of x, d x which is the integral from 0 to 1 of pi times big R of x squared minus pi times little r of x squared, d x. which is pi times the integral from 0 to 1 of the square root of x squared minus x squared squared. which is pi times the integral from 0 to 1 of x minus x to the fourth, d x.",
    block: true,
  )
]

#exercise[Evaluate the integral above.]

#theorem[Volume by Washers for Rotation about the #acc("x")-axis][
  For a solid of rotation formed by rotating a region around the #acc("x")-axis where you have the required bounds and radii in terms of #acc("x"), the volume is
  #math.equation(
    $V = integral_a^b A(x) dif x = pi integral_a^b [(R(x))^2 - (r(x))^2] dif x$,
    alt: "v equals is the integral from a to b of capital of x, d x. this is equal to pi times the integral from a to b of captial r of x squared minus little r of x squared, d x",
    block: true,
  )
]
#theorem[Volume by Washers for Rotation about the #acc("y")-axis][
  For a solid of rotation formed by rotating a region around the #acc("y")-axis where you have the required bounds and radii in terms of #acc("y"), the volume is
  #math.equation(
    $V = integral_a^b A(y) dif y = pi integral_a^b [(R(y))^2 - (r(y))^2] dif y$,
    alt: "v equals is the integral from a to b of capital of y, d y. this is equal to pi times the integral from a to b of captial r of y squared minus little r of y squared, d y",
    block: true,
  )
]

In other words,
#note-block[
  *Finding the Volume of a Solid of Revolution: Washer Method*
  1. Sketch both the region that is being rotated and the axis of revolution.
  2. Determine the variable of integration. Integration is performed with respect to the axis that is perpendicular to the slices.
  3. Determine the limits of integration. They must match the variable of integration!
  4. Derive a formula for the radii of the washer: #math.equation($R(x)" and "r(x)" (or "R(y)" and "r(y)" respectively)"$, alt: "captial r of x and little r of x, or captial r of y and little r of y respectively").
    - These are found by finding the distances of each curve from the axis of revolution. For more, see area between curves section.
  5. Integrate. Remember units in your final answer when applicable.
]

#example[
  Set up an integral to find the volume of the solid generated by revolving the region bounded by #math.equation($y=x^(2/3)$, alt: "y equals x to the two thirds power"), the #acc("x")-axis, and #math.equation($x=8$, alt: "x equals 8")
  #set enum(numbering: "a)")
  + around the #acc("x")-axis
  + around the #acc("y")-axis
  + around the line #math.equation($y=6$, alt: "y equals 6").
]
#my-solution-block[
  #set enum(numbering: "a)")
  + Sketching the region and an idea of the volume we make by rotating around the #acc("x")-axis we see the cross-sections are disks.
    #figure(image("figures/washerex3x.svg", alt: "todo"))
    Thus, the volume can be found with the disk method: by thinking of the cross-sectional area as a bunch of circles perpendicular to the #acc("x")-axis, from #math.equation($x=0" to "x=8$, alt: " x equals 0 to x equals 8").
    #math.equation(
      $
        V & = pi integral_0^8 (R(x))^2 dif x \
          & = pi integral_0^8 (x^(2/3))^2 dif x \
          & = pi integral_0^8 x^(4/3) dif x
      $,
      alt: "todo",
      block: true,
    )
  + Sketching the region and an idea of the volume we make by rotating around the #acc("y")-axis we see the cross-sections are washers now.
    #figure(image("figures/washerex3y.svg", alt: "todo"))
    Notice that we need to express the radii in terms of #acc("y") now, the large radius is always #math.equation($R(y)=8$, alt: "capital r of y equals 8") and the small radius is #math.equation($r(y)= y^(3/2)$, alt: "little r of y equals y to the three halves") which we got from solving the original equation for #acc("x"). Lastly, we note the solid fills space for #acc("y") in #closedint("0", "4"). Then the volume integral will be
    #math.equation(
      $
        V & = integral_0^4 pi[(R(y))^2 - (r(y))^2] dif y \
          & = integral_0^4 pi[(8)^2 - (y^(3/2))^2] dif y \
          & = pi integral_0^4 [64 - y^3] dif y \
      $,
      alt: "v equals the integral from 0 to 4 of pi times the quantity capital r of y squared minus little r of y squared, d y. Which is the integral from 0 to 4 of pi times the quantity 8 squared minus y to the power of three halves squared, d y. which is pi times the integral from 0 to 4 of 64 minus y cubed, dy.",
      block: true,
    )
  + Sketching the region and the horizontal line #math.equation($y=6$, alt: "y equals 6") we have
    #figure(image("figures/washerex3y6.svg", alt: "todo"))
    // todo: shade the region we are rotating in these figures
    We first find the radii, or the distance from #math.equation($y=6$, alt: "y equals 6") to the edges of the region. Note #math.equation($R$, alt: "big R") is always 6, and #math.equation($r=6-x^(2/3)$, alt: "little r is 6 minus x to the two thirds"). Then the area of each washer as a function of #acc("x") is
    #math.equation(
      $
        A(x) & = pi R^2 - pi r^2 \
             & = pi [6^2 - (6-x^(2/3))^2]
      $,
      alt: "A of x is pi times the quantity big r squared minus little r squared. Then plugging in the rs this equals pi times the quantity 6 squared minus 6 minus x to the two thirds all squared",
      block: true,
    )
    The washers fill the space from #math.equation($x = 0" to "x=8$, alt: "x equals 0 to x equals 8"), so the integral we use is #math.equation(
      $ V= pi integral_0^8 [6^2 - (6-x^(2/3))^2] dif x $,
      alt: "v equals pi times the integral from 0 to 8 of 6 squared minus 6 minus x to the two thirds all squared, d x.",
      block: true,
    )
]

#emph-block[
  6.2b Section Summary:
  - We used the area of a cross-section to develop disk and washer method for finding volumes of the solids of rotation.
  - We learned how to find the volumes of solids rotated about different horizontal and vertical lines.
]

