// chapter_5.typ

#import "./../../template_notes.typ": *
#show: template

// set up heading numbering
#set heading(numbering: "1.")
#counter(heading).update(6)
#context {
  if target() == "paged" and sys.inputs.at("individualchs", default: "false") == "true" {
    [#counter(heading).update(5)
      = Applications of Integrals
      #set document(title: "Section 6.3")]
  }
}
#context counter(heading).step(level: 2)
#context counter(heading).step(level: 2)

// any functions and templating you want for just this chapter can go here


== Volumes by Cylindrical Shells
#emph-block[
  6.3 Learning Objectives:
  - I can use shell method to find the volume of solids of rotation.
  - I can identify scenarios when shell or washer method is required for a problem based on its geometry.
]

#exercise[
  Spend 5-10 minutes trying to set up the integral for using washer method for the following problem. Then stop and analyze why this is particularly difficult.

  Rotate the region enclosed by the #acc("x")-axis and the parabola #math.equation($y = 3x - x^2$, alt: "y equals 3 x minus x squared") around the line #math.equation($x = -1$, alt: "x equals negative 1").
]
#my-solution-block[
  Note the plot of this region below
  #figure(image("figures/shellmotivation.svg", alt: "todo blah"))
  helps illustrate the difficulty. Simply put: We have no easy way of determining the radii, #math.equation($r" and "R$, alt: "little r and big r"), they are both the same function.
]

In the disk and washer method, the cross-sections taken were circular and perpendicular to the axis of rotation. We will introduce a new method, using a new shape for cross-sections, which are taken parallel to the axis of rotation.

Consider the following cookie cutters.
#figure(image(
  "figures/cookiecutter.jpg",
  alt: "a set of metal circular cookie cutters of varying sizes, all stacked within one another.",
  width: 45%,
  height: 20%,
))

For the next method, we will think of finding the area of concentric shells making up the shape, then integrating from the center of the shells to the edge to "add" up all the areas that go into the volume.

#theorem[Volume by Cylindrical Shells (for revolutions about vertical lines)][
  The formula of the solid generated by revolving the region bounded by the #acc("x")-axis, and the continuous function #math.equation($y=f(x) gt.eq 0$)  where #math.equation($L lt.eq a lt.eq x lt.eq b$) about the vertical line #math.equation($x=L$, alt: "x equals l"), is
  #math.equation(
    $V=integral_a^b 2 pi ("radius") f(x) dif x.\
    "where radius"=|L-x|" has been simplified"$,
    alt: "v equals the integral from a to b of 2 pi times the radius times f of x, d x where the radius is the absolute value of l minus x, simplified",
    block: true,
  )

  In general, the volume of the solid of a revolution sliced into cylindrical shells of radius, #math.equation($r(x)$, alt: "r of x"), and height, #math.equation($h(x)$, alt: "h of x"), is
  #math.equation(
    $V=integral_a^b 2pi |L-x| h(x) dif x.$,
    alt: "v equals the integral from a to b of 2 pi times aboslute value fo l minus x all times h of x, d x",
    block: true,
  )
]

To justify the previous formula, think about the area of one of the cookie cutters, or shells.

#example[
  Set up and evaluate the integral for the volume of the solid obtained by rotating the region #acc("R") about #math.equation($x=3$, alt: "x equals 3") where #acc("R") is the region enclosed by #math.equation($f(x)=4-2x, x=-1," and "y=2$, alt: "f of x equals 4 - 2x, x equals negative 1, and y equals 2."). Use shell method.
]

#my-solution-block[
  - The axis of rotation is perpendicular to #xaxis so we are integrating with respect to #acc("x") for shell method.
  - Sketching the region we have
    #figure(image("figures/triangleyshell.svg", alt: "todoo"))
  - #acc("h") is top curve minus bottom curve in this one, so #math.equation($h(x) = 4-2x-2 = 2-2x$, alt: "h of x is 4 minus 2 x minus 2 which is 2 minus x.")
  - #math.equation($r=|L-x|=|3-x|$, alt: "r equals the absolute value of l minus x which is the absolute value of 3 minus x"), and since the bounds go from #math.equation($-1" to "1$, alt: "minus 1 to 1") this is the same as #math.equation($r=3-x$, alt: "3 minus x").
  - The bounds (listed above) can be found from finding the left-most and right-most #acc("x") values of the region #acc("R").

  Altogether, the volume is
  #math.equation(
    $
      V & = integral_a^b 2 pi r(x) h(x) dif x \
        & = integral_(-1)^1 2 pi (3-x) (2-2x) dif x
    $,
    alt: "V equals the integral from a to b of 2 pi times r of x times h of x, d x. this is the integral from negative 1 to 1 of 2 pi times 3 minus x times 2 minus 2 x, dx",
    block: true,
  )
  To evaluate we multiply everything out so we can use power rule
  #math.equation(
    $
      V & = integral_(-1)^1 2 pi (3-x) (2-2x) dif x \
        & = 2 pi integral_(-1)^1 6-6x-2x+2x^2 dif x \
        & = 2 pi integral_(-1)^1 6-8x+2x^2 dif x \
        & = 2 pi [6x-4x^2+2/3 x^3]_(-1)^1 \
        & = 2 pi [(6-4+2/3)-(-6-4-2/3)] \
        & = 80/3 pi
    $,
    alt: "V is the integral from negative 1 to 1 of 2 pi times 3 minus x times 2 minus 2 x, dx. This is then ",
    block: true,
  )
]


#theorem[Volume by Cylindrical Shells (for revolutions about horizontal lines)][ //todo
  The formula of the solid generated by revolving the region bounded by the #acc("y")-axis, and the continuous function #math.equation($x=g(y) gt.eq 0$)  where #math.equation($L lt.eq a lt.eq y lt.eq b$) about the horizontal line #math.equation($y=L$, alt: "y equals l"), is
  #math.equation(
    $V=integral_a^b 2 pi ("radius") g(y) dif y.\
    "where radius"=|L-y|" has been simplified"$,
    alt: "v equals the integral from a to b of 2 pi times the radius times g of y, d y. where the radius is the absolute value of l minus y, simplified",
    block: true,
  )

  In general, the volume of the solid of a revolution sliced into cylindrical shells of radius, #math.equation($r(y)$, alt: "r of y"), and height, #math.equation($h(y)$, alt: "h of y"), is
  #math.equation(
    $V=integral_a^b 2pi |L-y| h(y) dif y.$,
    alt: "v equals the integral from a to b of 2 pi times absolute value of l minus y all times h of y, d y",
    block: true,
  )
]

#example[
  Set up the integral of the volume of the solid obtained by revolving the region #acc("R") enclosed by #math.equation($f(x) = sqrt(x), g(x) = 2-x$, alt: "f of x equals square root of x, g of x equals 2 minus x"), and the #xaxis about #math.equation($y=-1$, alt: "y equals negative 1"). (There may be more than one way to solve this problem, try shell now and see if washer works later. Compare and contrast both)
]
#my-solution-block[
  First we sketch the region, #acc("R"), and it's reflection across #math.equation($y=-1$, alt: "y equals negative 1"). Then we can start to sketch out the shell. Since we are rotating about an axis parallel to the #xaxis, we will integrate with respect to #acc("y") (for shell method). We find the functions intersect at #math.equation($(1,1)$, alt: "one comma one"). To find #math.equation($h(y)$, alt: "h of y"), we think about right function minus left function, and we need to write these in terms of #acc("y"). The right curve is given by #math.equation($x=2-y$, alt: "x equals 2 minus y"). The left curve, #math.equation($f(x)$, alt: "f of x"), is #math.equation($x=y^2$, alt: "x equals y squared"). So the height of each shell is #math.equation($h(y) = 2-y - y^2$, alt: "h of y is 2 minus y, minus y squared").
  The radius is #math.equation($r=|L-y|=y+1$, alt: "r equals absolute value of L minus y which is y plus 1"). The region #acc("R") has #acc("y") values from 0 to 1. Altogether,
  #math.equation(
    $
      V & = integral_0^1 2 pi r(y) h(y) dif y \
        & = integral_0^1 2 pi (y+1)(2-y-y^2) dif y
    $,
    alt: " v equals integral from 0 to 1 of 2 times pi times r of y times h of y, d y. The next line is the integral from o to 1 of 2 pi times y plus 1 times 2 minus y, minus y squared, d y ",
    block: true,
  )
]

#exercise[
  Use washer method to set up the integral for the above problem now. Practice writing both integrals as a limit of Riemann sums.
]

#example[
  Set up an integral to find the volume of the following solid:
  Rotate the region enclosed by the #acc("x")-axis and the parabola #math.equation($y = 3x - x^2$, alt: "y equals 3 x minus x squared") around the line #math.equation($x = -1$, alt: "x equals negative 1").
]

#my-solution-block[
  Our shells look like
  #figure(image("figures/shellmotivationsolved.svg", alt: "todo blah"))
  Then, the height is #math.equation($h(x)=3x-x^2$, alt: "h of x equals 3 x minus x squared"). Notice that since we did not revolve around the #acc("y")-axis, that the radius is not just #acc("x"). Instead, the radius is the distance between #acc("x") and #math.equation($x=-1$, alt: "x equals negative 1"). From area between curves we can think about "right curve minus left curve" to see that #math.equation($r(x) = x-(-1) = x+1$, alt: "r of x equals x minus negative 1 which is x plus 1").
  The integral for the volume is then
  #math.equation(
    $V = integral_0^3 2 pi (x+1)(3x-x^2) dif x$,
    alt: "v equals the integral from 0 to 3 of 2 pi times x plus 1 times 3x minus x squared, d x",
    block: true,
  )
]

#tip-block[
  Finding the Volume of a Solid of Revolution: Shell method
  + Sketch the region that is being rotated.
  + Draw the axis of rotation.
  + Determine the variable of integration. Integration is performed with respect to the axis that is perpendicular to the slices.
  + Derive a formula for the height of the shell. The shell height can be found by drawing a line parallel to the axis of rotation. This might be top curve minus bottom curve, or right curve minus left curve. Write this in terms of the variable of integration from the previous step.
    - #math.equation($|L-x| " or " |L-y|$, alt: "absolute value of l minus x or absolute value of l minus y") depending on variable of integration.
  + Determine the bounds of integration. They must match the variable of integration!
  + Integrate. Remember units in your final answer when applicable.
    - #math.equation($V = integral_a^b 2 pi r h dif x$, alt: "v equals the integral from a to b of 2 pi times r times h, d x.") or maybe with respect to #acc("y")
]

#exercise[
  Practice working out/evaluating all the unfinished integrals in this section. This is good practice, but not necessarily part of this section in a way.
]


#emph-block[
  6.3 Section Summary:
  - We learned when and how to use shell method to find the volume of solids of rotation.
]

